Add walltimemax for blues
The walltimemax attribute is now required for all queue settings.
Without this setting create_newcase will fail with the following
error message,

ERROR: Could not find walltime setting in config_batch.xml

Fixes #616